### ISSUE TITLE
Signup bugs

### ISSUE THREAD

**Issue by yujusti** [Blackshadow8910/CSC207-Project#18]
Right now we do not have any restrictions on who signs up with what information. I think that we should fix this issue by implementing new restrictions on what people can have as their usernames and passwords. This should be an easy implementation. I have listed some potential restrictions below:

- [x] Length Limits: Usually, usernames have a minimum and maximum length. A reasonable range is often between 3 and 30 characters.

- [x] Character Types: Specify the allowed character types (e.g., alphanumeric, letters only, or a combination). Avoid special characters that might cause issues in URLs or databases.

- [x] Case Sensitivity: Decide whether usernames are case-sensitive or case-insensitive. It's common for usernames to be case-insensitive to prevent confusion.

- [x] Length Requirements: Enforce a minimum password length to enhance security. A common recommendation is at least 8 characters.

- [x] Complexity: Encourage or require a mix of character types, including uppercase letters, lowercase letters, numbers, and special characters. This increases the password's strength.

- [x] No Username in Password: Prevent users from including their username or parts of it in their password.

I think these are some of the features we can add when a person signs up. Comment below if you think we should add some more or if some of these features are unreasonable.

**Comment by JimmyyNX** [comment]
I'm gonna make it so a password needs to have an uppercase character, a lowercase character, and a digit.
